version: "3"

services:
  node:
    image: node:latest
    tty: true
    stdin_open: true
    working_dir: /app
    volumes:
      - .:/app
      - node_modules:/app/node_modules

volumes:
  node_modules: